spring:
  application:
    name: bookstore

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # test
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    open-in-view: false

    # h2 db datasource
    h2:
      console:
        enabled: true
        path: /h2-console

    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb;MODE=MariaDB
      username: sa
      password:

    redis:
      host: localhost
      port: 6379
      # password:
      timeout: 10000ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  packages-to-scan: com.solve.bookstore.interfaces.web
  paths-to-match: /api/v1/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

cache:
  type: redis
  redis:
    time-to-live: 600000  # 10분